### ISSUE TITLE
Server render - ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ericelliott** [elementalui/elemental#108]
The following causes a reference error in Node:

```js
import elemental from 'elemental';
```

Full error output:

```sh
/Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:4
}},{key:"handleMutation",value:function(e){if("childList"===e.type){var t=s.default(e.addedNodes).filter(function(e){return e.nodeType===Node.ELEMENT_NODE});if(!t.length)return;var n=t.filter(this.isInsignificantBranch);n.forEach(a)}}},{key:"isInsignificantBranch",value:function(e){var t=p.default({context:e});if(t.some(function(e){return"true"===e.getAttribute("aria-hidden")}))return!1;var n=v.getParentComparator({element:e});return this._filter.some(n)?!1:!0}}]),e}();n.default=function(){var e=arguments.length<=0||void 0===arguments[0]?{}:arguments[0],t=e.context,n=e.filter,r=new g({context:t,filter:n});return{disengage:r.disengage}},t.exports=n.default},{"../get/insignificant-branches":14,"../get/parents":15,"../util/compare-position":76,"../util/node-array":80,"../util/toggle-attribute-value":83}],33:[function(e,t,n){"use strict";function r(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(n,"__esModule",{value:!0}

ReferenceError: window is not defined
    at Object.i.74 (/Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:4:26545)
    at o (/Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:2:553)
    at /Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:2:604
    at Object.i.53../supports-cache (/Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:4:17229)
    at o (/Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:2:553)
    at /Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:2:604
    at Object.i.64../detect-focus (/Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:4:22059)
    at o (/Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:2:553)
    at /Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:2:604
    at Object.i.28.../supports/focus-invalid-tabindex (/Users/eric/Dropbox/dev/universal-keystone/node_modules/ally.js/ally.min.js:2:25244)
```

**Comment by JedWatson** [comment]
I _think_ I've resolved that, will need to spin up the universal boilerplate and add Elemental to check though. It may be a hard break just importing the `ally` package otherwise :disappointed:

**Comment by thebigspoon** [comment]
I assume this turned out to be "a hard break" with `ally` given the following?

```bash
$ npm list elemental
├─┬ elemental@0.5.9
│ ├─┬ ally.js@1.0.1
│ │ ├── array.prototype.findindex@1.0.0
│ │ ├── css.escape@1.4.0
│ │ └── platform@1.3.0
│ ├── blacklist@1.1.2
│ └── history@1.16.0 extraneous
```

```bash
$ node
> require('elemental')
ReferenceError: window is not defined
    at Object.i.74 (/usr/local/src/django-conduit/example/node_modules/elemental/node_modules/ally.js/ally.min.js:4:26545)
    at o (/usr/local/src/django-conduit/example/node_modules/elemental/node_modules/ally.js/ally.min.js:2:553)
    at /usr/local/src/django-conduit/example/node_modules/elemental/node_modules/ally.js/ally.min.js:2:604
    at Object.i.53../supports-cache (/usr/local/src/django-conduit/example/node_modules/elemental/node_modules/ally.js/ally.min.js:4:17229)
    at o (/usr/local/src/django-conduit/example/node_modules/elemental/node_modules/ally.js/ally.min.js:2:553)
    at /usr/local/src/django-conduit/example/node_modules/elemental/node_modules/ally.js/ally.min.js:2:604
    at Object.i.64../detect-focus (/usr/local/src/django-conduit/example/node_modules/elemental/node_modules/ally.js/ally.min.js:4:22059)
    at o (/usr/local/src/django-conduit/example/node_modules/elemental/node_modules/ally.js/ally.min.js:2:553)
    at /usr/local/src/django-conduit/example/node_modules/elemental/node_modules/ally.js/ally.min.js:2:604
    at Object.i.28.../supports/focus-invalid-tabindex (/usr/local/src/django-conduit/example/node_modules/elemental/node_modules/ally.js/ally.min.js:2:25244)
```

**Comment by ericelliott** [comment]
yep.

**Comment by JedWatson** [comment]
Just updated to the latest beta, let's try it again. @thebigspoon can you let me know how this works out for you?

**Comment by rodneyrehm** [comment]
Hey @JedWatson, is there a reason you're using the UMD build (~100KB minified) rather than only the modules you really need? Right now I can only see you using [`ally.when.visibleArea`](https://github.com/elementalui/elemental/blob/6b5859f0be64ae6561062b722c362175d490bac2/src/components/Modal.js#L71), which by itself is round about 8KB minified.

**Comment by thebigspoon** [comment]
@JedWatson: `elemental@0.5.9` works for me now

**Comment by JedWatson** [comment]
Good point @rodneyrehm, related to #119 also. This is really an issue with `ally.js`, the `package.json` entry shouldn't point at a UMD build, but at the transpiled source. (UMD entry point is what you want for `bower.json`). I'll open an issue on the ally repo about this.

_Generally_ speaking, it's not best practice to include modules from a package directly (i.e. `require('ally.js/when/visible-area') is not good) because it explicitly ties your implementation to that package's internal structure (the React ecosystem used to see a lot of this happening with `react` itself, and stopping that has been the focus of a lot of refactoring this year)

The idea is that smart bundlers can then prune unused code... however thats not always a possibility today so we may find that it's still the best solution here to avoid the 100kb hit.

I started including individual modules from `ally.js` but there are a number of them used, including `ally.maintain` and `ally.when`

For now, this whole integration has introduced a lot of complexity that really needs a more comprehensive review before it's stable enough for general release so I've disabled it until we've got time to address it thoroughly.

**Comment by rodneyrehm** [comment]
> This is really an issue with ally.js, the package.json entry shouldn't point at a UMD build, but at the transpiled source. (UMD entry point is what you want for bower.json). I'll open an issue on the ally repo about this.

thank you! I made the UMD bundle the `main` script to simplify things for the general public, thinking that anyone who's able to use modules will understand how to switch to using them.

> Generally speaking, it's not best practice to include modules from a package directly […]

I'm open to suggestions! maybe we can discuss in the issue you're about to open? :)

> For now, this whole integration has introduced a lot of complexity that really needs a more comprehensive review before it's stable enough for general release so I've disabled it until we've got time to address it thoroughly.

let me know how I can help.

**Comment by nkbt** [comment]
I've created #118 recently, which sort of covers this case too, or at least a blocker.
