### ISSUE TITLE
FormSelect values can be object

### ISSUE THREAD

**Issue by annarichardson** [elementalui/elemental#195]
It would be nice is FormSelect values could be objects and not just strings (i.e. instead of this `{ label: 'Cooking', value: 'cooking' }`, be able to `{ label: 'Cooking', value: {name: 'cooking', id: 3 }}`. You are able to do this for the dropdown menu

**Comment by clschnei** [comment]
This is because the underlying DOM is using `<select>` elements [and just returning the element value](https://github.com/elementalui/elemental/blob/master/src/components/FormSelect.js#L122-L124). `<Dropdown>` is using `<li>`'s with [values bound to the callback](https://github.com/elementalui/elemental/blob/master/src/components/Dropdown.js#L90-L92).

This desired effect should be able to be achieved using the same technique, without breaking the existing API.

**Comment by jossmac** [comment]
@annarichardson thanks for contributing

This API is by design. You can derive the id via another method
