### ISSUE TITLE
There are more than two genders

### ISSUE THREAD

**Issue by sdaitzman** [elementalui/elemental#202]
http://elemental-ui.com/css
<img width="795" alt="screen shot 2017-05-28 at 5 38 52 pm" src="https://cloud.githubusercontent.com/assets/1499476/26532364/8c049752-43cc-11e7-940c-27a2020e0f44.png">

**Comment by jossmac** [comment]
I suppose you're referring to people who identify as a different gender to that which they were born.

That's true. It's also true that there are millions of better ways to address that than a snarky issue on an OSS project.

All the best,
jossmac

**Comment by jossmac** [comment]
@sdaitzman on a personal note:

There was likely an event (or many) that lead you to create this issue. I hope you're doing okay.

Best,
jossmac

**Comment by thejameskyle** [comment]
I've updated the table to be representative of more genders, and added a [code of conduct](https://github.com/elementalui/elemental/blob/master/code-of-conduct.md) with a contact email (james.kyle@thinkmill.com.au) to this repository so that it is available in the future. Thank you for raising this @sdaitzman 

<img width="785" alt="screen shot 2017-05-31 at 7 19 03 am" src="https://cloud.githubusercontent.com/assets/952783/26636470/c2af4732-45d1-11e7-9370-f86e7dc4c35c.png">

**Comment by JedWatson** [comment]
Thanks @thejameskyle for jumping in and addressing this.

@sdaitzman, I've removed earlier comments because I don't believe they came across the right way or represent the values of our team including the person who made them. Recognising diversity is an important issue in our industry and we're happy to help promote it.

**Comment by sdaitzman** [comment]
@JedWatson wow, thank you... I was going to write a response to the original comment, because I genuinely did not mean to be snarky. If any of the previous commenters want to discuss this more with me or do not understand why representation like this is important, I would be happy to talk more.
