### ISSUE TITLE
Update to React 0.14

### ISSUE THREAD

**Issue by JedWatson** [elementalui/elemental#77]
I propose we update for React 0.14 with a new version (0.5) and leave behind support for 0.13.

Although it's not strictly necessary to drop support for 0.13, upgrading will allow us (finally) to start using parent-based context for certain features like theme support and validation.

I think it will also help keep the codebase clean and free of warnings (including depending on `react-dom`, etc); there probably isn't any downside to staying on `elemental@0.4` for anyone who can't upgrade to `react@0.14` yet, other than missing out on new features going forward.

There's already a branch in place thanks to @NogsMPLS and @zackify.

Any objections?

**Comment by nkbt** [comment]
Looks totally reasonable to me.

**Comment by jossmac** [comment]
Can't wait :+1:

**Comment by NogsMPLS** [comment]
Heck yes!

I am curious on whether it should be a Major number increase instead of a Minor. But again, that's more a curiosity of whether semver increments should extend to major dependencies updating or not.

Minor obviously still works with the ^ symbol, which is probably the most common implementation anyways.

**Comment by JedWatson** [comment]
Done! I just pushed `v0.5.0`. @NogsMPLS SemVer standard for 0.x versions is that the minor behaves like a major, and patch like a minor _or_ a patch (so can be used for fixes _and_ non-breaking additions)
