### ISSUE TITLE
Pagination limit behaviour

### ISSUE THREAD

**Issue by jeffreypriebe** [elementalui/elemental#98]
Changed the "Limit" to 2 but it still shows 3 pages. In screenshot, it was the last value set.
![screenshot002](https://cloud.githubusercontent.com/assets/1160097/11384342/bb3c3e1e-92c3-11e5-83cb-e9dc1603818d.png)

**Comment by jossmac** [comment]
Your current page of `12` is invalid, which is skewing the results

**Comment by jeffreypriebe** [comment]
Fair point. I just tried it again with a valid page and it errors the same.
Values: 2, 25, Potatoes, Potato, 123, 2

In fact, I can't make Limit of "2" work with any values.

**Comment by jossmac** [comment]
@jeffreypriebe thanks for retesting

@MunGell would you mind having a look at this?

**Comment by MunGell** [comment]
@jossmac, yes, no problems

**Comment by MunGell** [comment]
Hey guys,

I've done some tests on this and actually recalled why it was designed that way.

This is expected behaviour &copy;  for all even "limit" numbers where Pagination adds +1 to center selected page in the middle (even covered with a test [here](https://github.com/elementalui/elemental/pull/58/files#diff-acf66ed1890f5d1e1c276218f9e9d0eeR110)). Basically, I was trying to [achieve](https://github.com/elementalui/elemental/pull/50#issuecomment-138211235) symmetry in pagination.

This is not the most obvious logic and I haven't documented it properly, sorry about that.

Please let me know if even number of pages is needed - I will change it accordingly.

**Comment by jeffreypriebe** [comment]
@MunGell I see the point about symmetry but it really does look wrong to an external user (even if there were documentation).

Using an even number also raises the question of which side to unbalance the page on (higher, lower, or changing depending on how many pages reside on each side of the current page).

**Comment by MunGell** [comment]
@jeffreypriebe sorry for late response, I will create a PR with these changes, so we will be able to test it.

**Comment by jossmac** [comment]
@MunGell perhaps we could add a `preverseSymmetry` prop?

**Comment by MunGell** [comment]
@jossmac yes, but this will add additional configuration parameter, which I was trying to avoid (not to overcomplicate component API).

To preserve symmetry developers could just ensure they pass odd number to `limit` prop.

I will change limit logic for even numbers to keep selected page on the left side. What do you think?

**Comment by jossmac** [comment]
@MunGell true, that's tidier. Sounds good man, thanks for looking into this
